spring.application.name=app-service

spring.cassandra.keyspace-name=url_keyspace
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.port=${CASSANDRA_PORT:9142}
spring.cassandra.contact-points=${CASSANDRA_CONTACT_POINTS:localhost}

# Expose Prometheus metrics for scraping by Grafana/Prometheus
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true